name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install golangci-lint
        run: |
          sudo curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.52.2
          sudo mv ./bin/golangci-lint /usr/local/bin/golangci-lint
      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m
        env:
          github_token: ${{ secrets.GIT_TOKEN }}
