name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/v1.52.2
      - name: Run golangci-lint and create issue on errors/warnings
        uses: 8398a7/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          golangci-lint-flangs: run --timeout 5m --issue-exit-code=3
          working_directory: .
