name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Install golangci-lint
        run: |
          sudo curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.42.1
      - name: Run golangci-lint
        run: ./bin/golangci-lint run --timeout=5m --out-format=github-actions
      - name: Creae issues for errors and warnings
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: 'golangci-lint report'
          content-filepath: ./golangci-lint-report.txt
  
