name: golangci-lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - uses: actions/checkout@v3
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Run golangci-lint
        run: golangci-lint run --timeout=5m --out-format=github-actions > golangci-lint-report.txt
      - name: Create Issue golangci-lint-report file
        if: ${{ always() }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: golangci-lint report
          content-filepath: ./golangci-lint-report.md
          labels: |
            report
            golangci-lint
        env:
          GITHUB_TOCKEN: ${{ secrets.GIT_TOCKEN }}
